#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

# Check if battery directories are detected
# [ ! -e /sys/class/power_supply/BAT?* ] && echo "No battery found" && exit 1

# Loop through all attached batteries and format the info
# for battery in /sys/class/power_supply/BAT?*
# do
# Sets up the status and capacity
# status=$(cat "$battery/status")
status=$(cat "/sys/class/power_supply/BAT0/status")
case "$status" in
	"Full") status="⚡" ;; # && setsid xcompmgr ;;
	"Discharging") status="🔋" && killall xcompmgr ;;
	"Charging") status="🔌";; # && setsid xcompmgr;;
	"Not charging") status="🛑" ;;
	"Unknown") status="♻" ;;
esac
capacity=$(cat "/sys/class/power_supply/BAT0/capacity")
# capacity=$(cat "$battery/capacity")
# Will make a warn variable if discharging and low
[ "$status" = "🔋" ] && [ "$capacity" -le 25 ] && local warn="❗"
# Prints the info
if [ "$capacity" -lt 10 ]
then
	notify-send "Low Battery $status $warn $capacity%!!!"
	notify-send "SHUTTING DOWN SHORTLY!!!"
elif [ "$capacity" -lt 5 ]
then
	notify-send 'SHUTTING DOWN NOW!'
	notify-send 'GOOD BUY MA FRIEND!'
fi

printf "%s%s%d%%\n" "$status" "$warn" "$capacity"
# done && return 0
