#!/bin/sh
# works on any init system
# requirements: dmenu, xorg-setxkbmap, dunst-git

kb="$(setxkbmap -query | grep -oP 'layout:\s*\K\w+')" || exit 1

case "$kb" in
	"us") setxkbmap gr && kb="🇬🇷" && echo "$kb" > /tmp/kblayout ;;
	"gr") setxkbmap us && kb="🇺🇸" && echo "$kb" > /tmp/kblayout ;;
esac

pkill -RTMIN+7 dwmblocks
notify-send "Keyboard Layout: $kb"
