#!/bin/sh

# Alsa
# echo 🔉$(amixer sget Master| awk '/dB/ {print($4)}')
# echo 🔉$(amixer sget Master | sed -e '$!d' -e 's|\].*||' -e 's| ||g' -e 's|^.*\[||')

# PulseAudio
vol=$(pulsemixer --get-volume | cut -d " " -f1)
mute=$(pulsemixer --get-mute)
if [ "$mute" -eq 1 ]
then
	echo 🔇
else
	echo "🔉$vol%"
fi
