#!/bin/sh

# Get user selection via dmenu from the pix dir.
chosen=$(exa -a -D -1 ~/media/pix/ | dmenu -i -l 30)

# Exit if none chosen.
[ -z "$chosen" ] && exit

sxiv -r "/home/manos/media/pix/$chosen/"
