#!/bin/sh

# Get user selection via dmenu from snippets file.
chosen=$(cut -d ';' -f1 ~/.local/share/snippets | dmenu -i -l 30)

# Exit if none chosen.
[ -z "$chosen" ] && exit

# Insert the snippets on the focused window.
xdotool type $(grep "$chosen" ~/.local/share/snippets | cut -d ';' -f2 )
