#!/bin/sh

# The famous "get a menu of emojis to copy" script but for bookmarks.

# Get user selection via dmenu from bookmarks file.
chosen=$(exa -a -D -1 ~/media/pix/ | dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

sxiv -r "/media/pix/$chosen"
