#!/bin/sh

# Get user selection via dmenu from snippets file.
chosen=$(cut -d ';' -f1 ~/.local/share/snippets | sed 's|^#.*||g' | sed '/^$/d' | dmenu -i -l 30)

# Exit if none chosen.
[ -z "$chosen" ] && exit

# Insert the snippets on the focused window.
snip=$(grep "$chosen" ~/.local/share/snippets | sed 's| *;|: |g')
notify-send 'Inserting' "$snip"&
snip=$(grep "$chosen" ~/.local/share/snippets | cut -d ';' -f2)
xdotool type "$snip"
