#!/bin/sh
dir="$HOME/media/pix/wallpapers/Cityscapes"

wall=$(exa -1 $dir | sort | shuf | shuf | shuf | shuf -n1)

rm -rf ~/.local/share/wallpaper
ln -s "$dir/$wall" "$HOME/.local/share/wallpaper"
xwallpaper --zoom "$HOME/.local/share/wallpaper"
